server:
  port: 8082

spring:
  application:
    name: second-service

  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instanceId: ${spring.application.name}:${server.port}
        prefer-ip-address: true