server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instanceId: ${spring.application.name}:${server.port}
        prefer-ip-address: true

#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        prefer-ip-address: true
#        health-check-path: ${server.servlet.context-path:}/actuator/health
#        health-check-interval: 15s
#        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}
#        service-name: ${spring.application.name}