spring:
#  cloud:
#    gateway:
#      routes:
#        - id: employeeModule
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/api/v1/**
#        - id: consumerModule
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/api/v2/**

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path:}/actuator/health
        health-check-interval: 15s
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: gateway-service

server:
  port: 8080